#!/bin/zsh

python plotting/table_generation.py problem_settings/circles_scalar_data.json problem_settings/circles_patch_data_2.json problem_settings/circles_patch_data_4.json problem_settings/circles_patch_data_8.json problem_settings/circles_patch_data_16.json problem_settings/circles_patch_data_32.json circles_data