#!/bin/zsh

python plotting/patches_fig_generation.py problem_settings/faces_patch_reg_2.json problem_settings/faces_patch_reg_4.json problem_settings/faces_patch_reg_8.json problem_settings/faces_patch_reg_16.json problem_settings/faces_patch_reg_32.json faces_reg