#!/bin/zsh

python plotting/patches_fig_generation.py problem_settings/cameraman_patch_data_2.json problem_settings/cameraman_patch_data_4.json problem_settings/cameraman_patch_data_8.json problem_settings/cameraman_patch_data_16.json problem_settings/cameraman_patch_data_32.json cameraman_data